### ISSUE TITLE
Connect to home assistant

### ISSUE THREAD

**Issue by ThoEngel** [thomasgermain/vr900-connector#3]
At issues #2 you describe your connection to home assistant. 
How do you connect your python script to home assistant?

**Comment by thomasgermain** [comment]
Here is the custom component zip I'm using, for now, temperature sensor, climate and water heater are supported and in read only mode.

[custom_components_vaillant.zip](https://github.com/thomasgermain/vr900-connector/files/2879390/custom_components_vaillant.zip)

Please be aware that it comes with no support yet, it's not even in a beta state

You just have to add this to your configuration.yaml
```yaml
vaillant:
  username: xxx
  password: yyy
```

**Comment by ThoEngel** [comment]
Cool, thank you.

**Comment by thomasgermain** [comment]
Hey,

just saw there was a big bang update (0.88)in HA for custom_components, here is the new structure.
Just unzip the content under custom_components, everything should work 
[vaillant.zip](https://github.com/thomasgermain/vr900-connector/files/2898427/vaillant.zip)

**Comment by ThoEngel** [comment]
This works great!!! Cool
