### ISSUE TITLE
Error for basic example: module 'vr900connector.api.urls' has no attribute 'facilities_list'

### ISSUE THREAD

**Issue by ThoEngel** [thomasgermain/vr900-connector#32]
Environment:
Version of vr900-connector 0.3.1 
Python 3.6.9 

If i start the basic example from github:

```
>>> from vr900connector.api import ApiConnector, urls
>>> connector = ApiConnector('myemail@email.com','mypassword')
>>> connector.get(urls.facilities_list()) 
```
I get the following error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'vr900connector.api.urls' has no attribute 'facilities_list'
```
What is going wrong?

**Comment by thomasgermain** [comment]
Hi,

you need to import the class inside the module `vr900connector.api.urls`
`from vr900connector.api import Urls`
then use `Urls.facilities_list()`

I'm gonna update the doc

**Comment by ThoEngel** [comment]
Yes it works.
