### ISSUE TITLE
Installation error o debian

### ISSUE THREAD

**Issue by lighthousehh** [thomasgermain/vr900-connector#44]
Hi Thomas!
#The installation via pip errored:
Collecting vr900-connector
  Using cached https://files.pythonhosted.org/packages/d2/3c/b2c91b00e7e594a8cc99504fc7b6230e21cbdd7f6a4a9309a1146ffb350c/vr900-connector-0.3.4.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-PB1Co9/vr900-connector/setup.py", line 6, in <module>
        with open(path.join(this_directory, 'README.md'), encoding='utf-8') as f:
    TypeError: 'encoding' is an invalid keyword argument for this function
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-PB1Co9/vr900-connector/

What could be my mistake in this case?
BR Thomas

**Comment by lighthousehh** [comment]
Sorry, I took the wrong python version.
Thomas

**Comment by thomasgermain** [comment]
You're right.

Please let me know if you have other issues
